### ISSUE TITLE
Defect in Synonym Swap for "Dr. Mark Lombardi"

### ISSUE THREAD

**Issue by grafflr2** [grafflr/deepnlu#28]
Given this test harness
```python
svcresult = api.handle_text(
    input_text=input_text,
    ontologies=['TestDN028'],
    absolute_path=absolute_path)

csvresult = api.to_csv(svcresult, include_position=False)
return [x['Canon'] for x in csvresult]
```

this assertion works
```python
assert 'mark_lombardi' in execute("Mark Lombardi")
```

and this assertion fails
```
assert 'mark_lombardi' in execute("Dr Mark Lombardi")
```

The associated text file contains
```
mark_lombardi~dr mark_lombardi,dr. mark_lombardi
```

The error message is
```
2022-06-01 16:29:13,709 : ERROR : exact_match_swapper.py : process() : 62 : Canonical Form Not Found
        Input Tokens: dr_mark_lombardi
Traceback (most recent call last):
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\tests\test_regression_DN028.py", line 48, in <module>
    main()
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\tests\test_regression_DN028.py", line 44, in main
    test_001()
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\tests\test_regression_DN028.py", line 40, in test_001
    assert 'mark_lombardi' in execute("Dr Mark Lombardi")
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\tests\test_regression_DN028.py", line 26, in execute
    svcresult = api.handle_text(
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\bp\deepnlu_api.py", line 105, in handle_text
    return svc.process(input_text)
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\svc\parse_text_oneshot.py", line 84, in process
    paragraphs.append([self._handle_sentence(x)
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\svc\parse_text_oneshot.py", line 84, in <listcomp>
    paragraphs.append([self._handle_sentence(x)
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\recipe\dmo\sentence_handler_oneshot.py", line 123, in process
    tokens = self._swap_synonyms(tokens)
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\services\mutato\bp\mutato_api.py", line 80, in swap
    swaps = self._perform_exact_matching(tokens)
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\services\mutato\svc\perform_exact_matching.py", line 87, in process
    swaps = self._process(tokens)
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\services\mutato\svc\perform_exact_matching.py", line 64, in _process
    d_swap = self._exact_match_swapper(results)
  File "C:\Users\Craig\git\graffl\deepnlu\deepnlu\services\mutato\dmo\exact_match_swapper.py", line 65, in process
    raise ValueError
ValueError
```

I suspect the external text file is being used to generate the candidate, but is not being used to validate the candidate.

**Comment by grafflr2** [comment]
The failure occurs within `exact_match_swapper.py` at this point:
```python
for tokens in candidate_tokens:

    normal = [x['normal'] for x in tokens]
    input_text = '_'.join(normal).strip().lower()

    canon = self._find_canon(input_text)
    if self.isEnabledForDebug:
        Enforcer.is_optional_str(canon)

    if not canon:
        self.logger.error('\n'.join([
            "Canonical Form Not Found",
            f"\tInput Tokens: {input_text}"]))
        raise ValueError
```

I am puzzled as to why the algorithm does not check the variants as well as the canons. 

It would seem that both are necessary for validation.

**Comment by grafflr2** [comment]
Adding these last values worked
```
mark_lombardi~...,dr mark lombardi, dr. mark lombardi
```

This concerns me as I would have thought the synonym swapper was recursive enough to not require this.

**Comment by grafflr2** [comment]
But as far as this test case and defect goes, I have a viable work-around and that should be sufficient.

**Comment by grafflr2** [comment]
This still bothers me - I feel like the lookup table should have handed this.

When I examine the contents of lookup for bigrams, I get this
```json
 [
    'dr._mark lombardi',
    'dr_mark lombardi',
    'dr. lombardi’s',
    'dr. lombardis',
    'mark lombardi',
    'dr. lombardi',
]
```

That's kind of a puzzling output.

Where's `dr mark_lombardi`?

And why does lookup create `dr_mark lombardi`?

I assumed the purpose of lookup was to form entities that actually exist somewhere, not perform random concatenations.

**Comment by grafflr2** [comment]
Or, it's going to be random, why don't we have
```
 [
   "dr._mark lombardi",
   "dr. mark_lombardi",
   "dr_mark lombardi",
   "dr mark_lombardi",
   "dr. lombardi’s",
   "dr. lombardis",
   "mark lombardi",
   "dr. lombardi"
]

**Comment by grafflr2** [comment]
But that doesn't seem correct.

The view generator is staffed with the output from the synonym generator.

```json
{
   "mark_lombardi":[
      "dr. lombardi",
      "dr. lombardis",
      "mark lombardi",
      "dr. lombardi’s",
      "dr. mark lombardi",
      "dr. mark_lombardi",
      "dr mark_lombardi"
   ]
}
```

**Comment by grafflr2** [comment]
I can see that the output generation from `OwlSpanGenerator` has a lot of duplicates:
```json
{
   "3":[
      "apple distinguished school",
      "apple distinguished school",
      "bachelor of arts",
      "bachelor of arts",
      "bachelor of science",
      "bachelor of science",
      "educate to careers",
      "educate to careers",
      "field of study",
      "field of study",
      "dr. mark lombardi",
      "dr. mark lombardi",
      "dr mark lombardi",
      "master of arts",
      "master of arts",
      "master of science",
      "master of science",
      "ncaa division i",
      "ncaa division ii",
      "ncaa division iii",
      "ohio state university",
      "ohio state university",
      "mobile learning environment",
      "return on investment",
      "return on investment",
      "student life program",
      "student life program",
      "propn propn university"
   ]
}
```

**Comment by grafflr2** [comment]
This is the new lookup dictionary:
```json
{
   "1":[
      "president!university",
      "academic!program",
      "athletic!program",
      "fastest-growing",
      "student-athlete",
      "organization",
      "recognition",
      "environment",
      "chairperson",
      "graduation",
      "interviews",
      "chairwoman",
      "excellence",
      "enrollment",
      "commission",
      "innovation",
      "university",
      "leadership",
      "education",
      "diversity",
      "doctorate",
      "publisher",
      "president",
      "location",
      "pedagogy",
      "speeches",
      "chairman",
      "increase",
      "tripled",
      "company",
      "student",
      "athlete",
      "publish",
      "equity",
      "mentor",
      "degree",
      "metric",
      "tenure",
      "person",
      "author",
      "school",
      "event",
      "agent",
      "state",
      "skill",
      "apple",
      "award",
      "city",
      "role",
      "roi"
   ],
   "2":[
      "student_athlete_graduation rate",
      "student athlete_graduation_rate",
      "chronicle_of_higher education",
      "chronicle of_higher_education",
      "mobile learning_environment",
      "st. louis_sports_commission",
      "mobile_learning environment",
      "st._louis_sports commission",
      "apple_distinguished school",
      "apple distinguished_school",
      "st_louis_sports commission",
      "st louis_sports_commission",
      "international relations",
      "propn_propn university",
      "propn propn_university",
      "ohio_state university",
      "ohio state_university",
      "return_on investment",
      "return on_investment",
      "university president",
      "undergraduate degree",
      "student life!program",
      "distinguished school",
      "maryville university",
      "student_life program",
      "student life_program",
      "bachelor of_science",
      "increase enrollment",
      "academic excellence",
      "bachelor_of science",
      "remote environment",
      "educate_to careers",
      "educate to_careers",
      "dr._mark lombardi",
      "master of_science",
      "sports commission",
      "ncaa_division iii",
      "political science",
      "dr. mark_lombardi",
      "purdue university",
      "master_of science",
      "ncaa division_iii",
      "propn university",
      "athletic program",
      "academic program",
      "dr_mark lombardi",
      "bachelor_of arts",
      "presidents award",
      "ncaa_division ii",
      "bachelor of_arts",
      "ncaa division_ii",
      "dr mark_lombardi",
      "higher education",
      "fastest growing",
      "master's degree",
      "graduation rate",
      "public speaking",
      "ncaa_division i",
      "student athlete",
      "president award",
      "graduate degree",
      "bachelor degree",
      "ncaa division_i",
      "campus program",
      "field of_study",
      "field_of study",
      "master_of arts",
      "dr. lombardi’s",
      "master of_arts",
      "master degree",
      "mark lombardi",
      "ncaa division",
      "dr. lombardis",
      "dr. lombardi",
      "chair woman",
      "st. louis",
      "the chair",
      "chair man",
      "chair of",
      "st louis"
   ],
   "3":[
      "mobile learning environment",
      "apple distinguished school",
      "propn propn university",
      "ohio state university",
      "return on investment",
      "student life program",
      "bachelor of science",
      "educate to careers",
      "dr. mark lombardi",
      "master of science",
      "ncaa division iii",
      "ncaa division ii",
      "dr mark lombardi",
      "bachelor of arts",
      "ncaa division i",
      "field of study",
      "master of arts"
   ],
   "4":[
      "student athlete graduation rate",
      "chronicle of higher education",
      "st. louis sports commission",
      "st louis sports commission"
   ],
   "5":[
      
   ],
   "6":[
      
   ]
}
```

**Comment by grafflr2** [comment]
It appears to be a positive thing that I have this entry `"dr mark_lombardi"` in grams[2] of the lookup dictionary.

This is helpful when forming a candidate using the slider, but not so helpful when it comes to finding a canonical entry.

That's understandable because `dr mark lombardi` is not an OWL entity; it's a synonym.  

The technique of creating `dr mark_lombardi` simply exists to help deal with recursion.  

But can't I look this up as a variant, and find the canon that way?

**Comment by grafflr2** [comment]
Reverse Synonyms has this
```python
 'dr mark_lombardi': ['mark_lombardi'],
 'dr. lombardi': ['mark_lombardi'],
 'dr. lombardis': ['mark_lombardi'],
 'dr. lombardi’s': ['mark_lombardi'],
 'dr. mark lombardi': ['mark_lombardi'],
 'dr. mark_lombardi': ['mark_lombardi'],
```

This is all very complicated.

The relationship between lookups and synonyms is neither well-defined nor well understood.

**Comment by grafflr2** [comment]
I find this defect irritating

Given this
![image](https://user-images.githubusercontent.com/91857201/171751851-8bcf369a-83b6-452d-991f-7f24e1b95895.png)

And given this
```python

**Comment by grafflr2** [comment]
This may be related to tokenization.

Consider that the synonym `Dr. Mark Lombardi` may be treated as 3 tokens vs spaCy 4 tokens [`Dr`, `.`, `Mark`, `Lombard`]

**Comment by grafflr2** [comment]
This also works - note the space between `Dr . Mark Lombardi`
![image](https://user-images.githubusercontent.com/91857201/171752672-42f1eef0-b970-4818-95a7-762b54cd7b2c.png)

**Comment by grafflr2** [comment]
My fix had to be resolved in the `synonyms()` function within **ask-owl**.  At that layer, I take any synonym with a period and tokenized that out. 

For example:
```
alpha.beta --> alpha . beta
dr. strange --> dr . strange
```
